[package]
name = "otools-platform-shortcuts"
version = "0.1.0"
edition = "2021"

[dependencies]
otools-core = { path = "../../core" }
otools-plugin-config = { path = "../../plugins/config/host" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-global-shortcut = "2"
