[package]
name = "otools-platform-native"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
otools-core = { path = "../../core" }
otools-platform-host-dispatch = { path = "../host-dispatch", default-features = false }
otools-platform-native-contract = { path = "../native-contract" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
