[package]
name = "otools-host"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
dirs = "6"
otools-ai = { path = "../ai" }
otools-core = { path = "../core" }
otools-platform-host = { path = "../platform/host" }
otools-platform-filesystem = { path = "../platform/filesystem" }
otools-platform-native = { path = "../platform/native" }
otools-plugin-state = { path = "../platform/plugin-state" }
otools-plugin-config = { path = "../plugins/config/host" }
otools-plugin-dev = { path = "../plugins/dev/host" }
otools-plugin-park = { path = "../plugins/park/host" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
