[package]
name = "otools-platform-package-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
encoding_rs = "0.8"
windows-sys = { version = "0.59", features = ["Win32_Globalization"] }
