[package]
name = "otools-plugin-park"
version = "0.1.0"
edition = "2021"

[dependencies]
otools-core = { path = "../../../core" }
otools-plugin-park-catalog = { path = "../catalog" }
otools-plugin-park-download = { path = "../download" }
otools-plugin-park-install = { path = "../install" }
otools-plugin-park-local-catalog = { path = "../local-catalog" }
otools-plugin-park-install-record = { path = "../install-record" }
otools-plugin-park-installed = { path = "../installed" }
otools-plugin-park-workspace = { path = "../workspace" }
otools-plugin-support = { path = "../../support" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
