[package]
name = "otools-platform-host"
version = "0.1.0"
edition = "2021"

[dependencies]
otools-core = { path = "../../core" }
otools-platform-clipboard = { path = "../clipboard" }
otools-platform-http-client = { path = "../http-client" }
otools-platform-package-manager = { path = "../package-manager" }
otools-platform-process = { path = "../process" }
otools-platform-project = { path = "../project" }
otools-platform-shell = { path = "../shell" }
otools-platform-storage = { path = "../storage" }
otools-platform-upload = { path = "../upload" }
otools-platform-webview-fs = { path = "../webview-fs" }
serde_json = "1"
otools-platform-ssh = { path = "../ssh" }
